apiVersion: platform.lzaas/v1alpha1
kind: XProject
metadata:
  name: lzaas-dev-test
spec:
  appCode: test
  env: dev
  billingAccount: 01F5C7-399448-A2BCF8
  # folderName: 181428570708
  labels:
    tenant: platform
    cost-center: platform
